guiderun-project/backend

run/src/main/java/com/guide/run/gloabl/jwt/JwtAuthenticationFilter.java, run/src/main/java/com/guide/run/gloabl/security/config/SecurityConfig.java, run/src/main/java/com/guide/run/user/controller/SignController.java, run/src/main/java/com/guide/run/user/entity/Role.java, run/src/main/java/com/guide/run/user/entity/User.java, run/src/main/java/com/guide/run/user/response/LoginResponse.java
기존 social Login 로직 삭제
-> 기존 로직 삭제
-> 카카오 인가 코드 받으면
-> 자체 엑세스 토큰 발급
=> Social Login 로직 변경

run/build.gradle, run/src/main/java/com/guide/run/user/controller/SignController.java, run/src/main/java/com/guide/run/user/dto/GuideSignupDto.java, run/src/main/java/com/guide/run/user/dto/ViSignupDto.java, run/src/main/java/com/guide/run/user/service/GuideService.java, run/src/main/java/com/guide/run/user/service/UserService.java, run/src/main/java/com/guide/run/user/service/ViService.java
=> GUIDE-83 전화번호 숫자 패턴 처리 및 저장 -> GUIDE-82로 머지

run/src/main/java/com/guide/run/temp/member/dto/EventDTO.java, run/src/main/java/com/guide/run/temp/member/service/ExcelService.java, run/src/main/java/com/guide/run/user/controller/SignController.java, run/src/main/java/com/guide/run/user/dto/ViSignupDto.java, run/src/main/java/com/guide/run/user/dto/request/AccountIdDto.java, run/src/main/java/com/guide/run/user/dto/response/IsDuplicatedResponse.java, run/src/main/java/com/guide/run/user/dto/response/SignupResponse.java, run/src/main/java/com/guide/run/user/service/GuideService.java, run/src/main/java/com/guide/run/user/service/MypageService.java, run/src/main/java/com/guide/run/user/service/SignupInfoService.java, run/src/main/java/com/guide/run/user/service/ViService.java
- 엑셀 파일 row와 column에 맞게 엑셀 저장 로직 수정
- 아이디 중복 확인 누락된 부분 구현
- 수정되지 않거나 누락된 필드 수정하고 추가
=> Fix : GUIDE - 104 엑셀 db 저장 버그 수정+기타 버그 개선

run/src/main/java/com/guide/run/temp/member/service/ExcelService.java
=> Fix : 엑셀  service 수정

run/src/main/java/com/guide/run/user/controller/SignController.java, run/src/main/java/com/guide/run/user/dto/ReissuedAccessTokenDto.java
=> fix : 엑세스 토큰 재발급 수정

run/src/main/java/com/guide/run/global/cookie/service/CookieService.java, run/src/main/java/com/guide/run/user/controller/SignController.java
=> G UI de 70 이벤트 crud

run/src/main/java/com/guide/run/temp/member/repository/AttendanceRepository.java, run/src/main/java/com/guide/run/temp/member/repository/AttendanceRepositoryImpl.java, run/src/main/java/com/guide/run/user/controller/SignupInfoController.java, run/src/main/resources/application-qa.yml
충돌 해결 및 s3 설정 추가
충돌 해결 및 s3 설정 추가
Resolves: 
See also:
=> ftx : 충돌 해결 및 s3 설정 추가

run/src/main/java/com/guide/run/event/entity/repository/EventRepositoryImpl.java, run/src/main/java/com/guide/run/global/s3/S3Uploader.java, run/src/main/java/com/guide/run/user/info/GetNaverInfo.java, run/src/main/java/com/guide/run/user/service/ProviderService.java, run/src/main/resources/application-local.yml
=> fix : 네이버 로그인 로직 수정, s3 설정파일 수정

run/src/main/java/com/guide/run/temp/member/repository/AttendanceRepository.java
=> fix : 출석 요청 로직 수정

run/src/main/java/com/guide/run/global/s3/S3Uploader.java, run/src/main/java/com/guide/run/global/security/config/SecurityConfig.java, run/src/main/java/com/guide/run/user/service/ImgService.java
s3 업로드 실패 에러 fix
s3 업로드 실패 에러 fix
Resolves: 
See also:
=> fix : s3 업로드 실패 에러 해결

run/src/main/java/com/guide/run/admin/dto/EventTypeCountDto.java, run/src/main/java/com/guide/run/admin/service/AdminEventService.java, run/src/main/java/com/guide/run/event/controller/EventController.java, run/src/main/java/com/guide/run/event/entity/repository/EventFormRepository.java, run/src/main/java/com/guide/run/event/entity/repository/EventRepositoryImpl.java, run/src/main/java/com/guide/run/event/service/EventFormService.java, run/src/main/java/com/guide/run/event/service/EventService.java, run/src/main/java/com/guide/run/global/scheduler/SchedulerService.java, run/src/main/java/com/guide/run/global/security/config/SecurityConfig.java, run/src/main/java/com/guide/run/user/controller/ImgController.java, run/src/main/java/com/guide/run/user/controller/LoginInfoController.java, run/src/main/java/com/guide/run/user/controller/MypageController.java, run/src/main/java/com/guide/run/user/dto/response/ImgResponse.java, run/src/main/java/com/guide/run/user/service/MypageService.java
온보딩 버그 픽스
1. 일반 로그인 엑세스 토큰 설정 변경
2. 아이디/비밀번호 찾기도 엑세스 토큰 설정 변경 
마이페이지 버그 픽스
1. event-type 개수 확인 404 처리
2. 이미지 첨부 안됨 (확실하지 않음)
4. 이벤트 팝업 서버 에러 처리(확실하지 않음..)
--
기능 수정
1. 모집 마감/이벤트 종료 스케줄러 처리 
- 생성 당일 모집 시 이벤트 모집 시작으로 생성 시 변경
- 이벤트 시작시간이 되면 모집 종료로 변경
온보딩 버그 픽스 : SecurityConfig 수정
마이페이지 버그 픽스
1. event-type 개수 확인 404 처리 -> userId 누락 수정.
2. 이미지 첨부 안됨 (확실하지 않음)  -> 파라미터 files로 변경
4. 이벤트 팝업 서버 에러 처리(확실하지 않음..) -> eventForm 조회 시 orElse로 null 반환
Resolves: 
See also:
=> fix : 마이페이지, 온보딩 버그 수정, 스케줄러 로직 변경

run/src/main/java/com/guide/run/admin/dto/EventTypeCountDto.java, run/src/main/java/com/guide/run/admin/service/AdminEventService.java, run/src/main/java/com/guide/run/event/controller/EventController.java, run/src/main/java/com/guide/run/event/entity/repository/EventFormRepository.java, run/src/main/java/com/guide/run/event/entity/repository/EventRepositoryImpl.java, run/src/main/java/com/guide/run/event/service/EventFormService.java, run/src/main/java/com/guide/run/event/service/EventService.java, run/src/main/java/com/guide/run/global/scheduler/SchedulerService.java, run/src/main/java/com/guide/run/global/security/config/SecurityConfig.java, run/src/main/java/com/guide/run/user/controller/ImgController.java, run/src/main/java/com/guide/run/user/controller/LoginInfoController.java, run/src/main/java/com/guide/run/user/controller/MypageController.java, run/src/main/java/com/guide/run/user/dto/response/ImgResponse.java, run/src/main/java/com/guide/run/user/service/MypageService.java
온보딩 버그 픽스
1. 일반 로그인 엑세스 토큰 설정 변경
2. 아이디/비밀번호 찾기도 엑세스 토큰 설정 변경 
마이페이지 버그 픽스
1. event-type 개수 확인 404 처리
2. 이미지 첨부 안됨 (확실하지 않음)
4. 이벤트 팝업 서버 에러 처리(확실하지 않음..)
--
기능 수정
모집 마감/이벤트 종료 스케줄러 처리 
- 생성 당일 모집 시 이벤트 모집 시작으로 생성 시 변경
- 이벤트 시작시간이 되면 모집 종료로 변경
온보딩 버그 픽스 
- SecurityConfig 수정
마이페이지 버그 픽스
1. event-type 개수 확인 404 처리 -> userId 누락 수정.
2. 이미지 첨부 안됨 (확실하지 않음)  -> 파라미터 files로 변경
4. 이벤트 팝업 서버 에러 처리(확실하지 않음..) -> eventForm 조회 시 orElse로 null 반환
Resolves: 
See also:
=> Fix 마이페이지 온보딩 버그 수정, 이벤트 스케줄러 변경

run/src/main/java/com/guide/run/event/entity/repository/EventFormRepository.java, run/src/main/java/com/guide/run/event/service/EventFormService.java, run/src/main/java/com/guide/run/event/service/EventService.java, run/src/main/java/com/guide/run/global/s3/S3Uploader.java, run/src/main/java/com/guide/run/user/controller/LoginInfoController.java, run/src/main/java/com/guide/run/user/dto/request/AuthNumRequest.java, run/src/main/java/com/guide/run/user/dto/request/NewPasswordDto.java
이벤트 팝업 조회 에러 수정
매칭이 null일 때 처리 과정 추가
Resolves: 
See also:
=> fix : 이벤트 팝업 조회 에러 수정, 이미지 업로드 확인용 로그 추가

run/src/main/java/com/guide/run/event/service/EventService.java, run/src/main/java/com/guide/run/user/controller/LoginInfoController.java
노션 API 문서와 다르게 매핑된 api endpoint 수정
=> Fix 마이페이지 온보딩 버그 수정

run/src/main/java/com/guide/run/event/entity/dto/response/EventPopUpResponse.java, run/src/main/java/com/guide/run/event/service/EventService.java
=> fix : 이벤트 팝업 필드 누락 수정

run/src/main/java/com/guide/run/event/entity/dto/response/EventPopUpResponse.java, run/src/main/java/com/guide/run/event/service/EventService.java, run/src/main/java/com/guide/run/user/controller/LoginInfoController.java
recruitVi, recruitGuide가 누락되어 수정함.
=> Fix : 이벤트 팝업 모집 인원 필드 누락 수정

run/src/main/java/com/guide/run/user/controller/LoginInfoController.java, run/src/main/java/com/guide/run/user/dto/request/TmpTokenDto.java
@RequsetBody에 dto가 들어가지 않아서 생긴 오류.
dto 생성해서 넣어주었음.
=> fix : 아이디 찾기 시 토큰 에러 수정

run/src/main/java/com/guide/run/event/entity/dto/response/EventPopUpResponse.java, run/src/main/java/com/guide/run/event/service/EventService.java
=> fix : 이벤트 팝업에 주최자 안 뜨는 에러 수정

run/src/main/java/com/guide/run/event/entity/dto/response/EventPopUpResponse.java, run/src/main/java/com/guide/run/event/service/EventService.java
String 타입이면 null로 반환하는 문제 발생. UserType으로 변경하여 response 반영
=> fix : 이벤트 팝업 null 에러 수정

run/src/main/java/com/guide/run/event/entity/dto/response/EventPopUpResponse.java, run/src/main/java/com/guide/run/event/service/EventService.java
=> fix : 이벤트 팝업 조회 수정

run/src/main/java/com/guide/run/event/service/EventService.java
=> fix : 이벤트 팝업 에러 수정

run/src/main/java/com/guide/run/event/controller/EventFormController.java, run/src/main/java/com/guide/run/event/entity/dto/response/form/Form.java, run/src/main/java/com/guide/run/event/entity/dto/response/form/GetAllForms.java, run/src/main/java/com/guide/run/event/entity/dto/response/match/MatchedGuideInfo.java, run/src/main/java/com/guide/run/event/entity/dto/response/match/MatchedViInfo.java, run/src/main/java/com/guide/run/event/entity/repository/EventFormRepository.java, run/src/main/java/com/guide/run/event/entity/repository/EventFormRepositoryCustom.java, run/src/main/java/com/guide/run/event/entity/repository/EventFormRepositoryImpl.java, run/src/main/java/com/guide/run/event/entity/repository/EventRepositoryImpl.java, run/src/main/java/com/guide/run/event/service/EventFormService.java, run/src/main/java/com/guide/run/event/service/EventMatchingService.java, run/src/main/java/com/guide/run/partner/entity/matching/repository/MatchingRepositoryImpl.java, run/src/main/java/com/guide/run/partner/entity/matching/repository/UnMatchingRepositoryImpl.java, run/src/main/java/com/guide/run/temp/member/repository/AttendanceRepositoryImpl.java
=> Guide-192 좋아요 테이블 수정후 로직 수정

run/src/main/java/com/guide/run/event/entity/repository/EventRepositoryImpl.java, run/src/main/java/com/guide/run/event/service/EventGetService.java
=> G UI de 192 좋아요 테이블 수정후 로직 수정

run/src/main/java/com/guide/run/partner/entity/dto/MyPagePartner.java
=> fix : 마이페이지 파트너 안 뜨는 에러 수정

run/src/main/java/com/guide/run/event/entity/repository/EventRepositoryImpl.java
=> fix : 조회 날짜순 정렬 수정

run/src/main/java/com/guide/run/admin/dto/response/user/NewUserResponse.java, run/src/main/java/com/guide/run/partner/entity/partner/repository/PartnerLikeRepository.java, run/src/main/java/com/guide/run/user/service/UserService.java
- 좋아요 테이블 변경으로 생긴 회원 탈퇴 에러 수정
- 어드민 새로 가입한 회원 리스트 에러 수정
=> fix : 회원 탈퇴, 새로 가입한 회원 리스트 버그 픽스

run/src/main/java/com/guide/run/event/entity/dto/response/comments/GetComment.java, run/src/main/java/com/guide/run/event/entity/dto/response/get/DetailEvent.java, run/src/main/java/com/guide/run/event/entity/repository/EventFormRepository.java, run/src/main/java/com/guide/run/event/entity/repository/EventRepository.java, run/src/main/java/com/guide/run/event/service/EventGetService.java
=> fix : created_at 초단위 삭제

run/src/main/java/com/guide/run/event/entity/dto/response/get/DetailEvent.java, run/src/main/java/com/guide/run/event/service/EventService.java
=> fix : 이벤트 상세 조회 모집인원 참여 인원 구분

run/src/main/java/com/guide/run/event/entity/dto/response/get/DetailEvent.java
=> fix : 이벤트 모집 인원 참여 인원 구분

run/src/main/java/com/guide/run/event/entity/dto/response/get/MyEventDday.java
=> fix : dDay 조회 수정

run/src/main/java/com/guide/run/event/service/EventFormService.java
=> fix : 신청서 신청 수정

run/src/main/java/com/guide/run/event/entity/dto/response/get/DetailEvent.java, run/src/main/java/com/guide/run/event/service/EventService.java
=> fix : 상세조회 수정

run/src/main/java/com/guide/run/event/service/EventService.java
=> fix : 이벤트 모집 마감 변경

run/src/main/java/com/guide/run/event/service/EventService.java, run/src/main/java/com/guide/run/partner/entity/matching/repository/MatchingRepositoryImpl.java, run/src/main/java/com/guide/run/partner/entity/matching/repository/UnMatchingRepositoryImpl.java
=> G UI de 192 매칭 관련 로직 수정

run/src/main/java/com/guide/run/event/entity/repository/EventRepositoryAdminImpl.java
=> fix : 마이페이지 이벤트 히스토리 year 조건 수정

run/src/main/java/com/guide/run/event/entity/repository/EventRepositoryImpl.java
=> fix : 년도별 sort 조회 적용

run/src/main/java/com/guide/run/event/service/EventMatchingService.java, run/src/main/java/com/guide/run/partner/entity/matching/repository/MatchingRepository.java
=> fix : 매칭 관련  로직 수정

run/src/main/java/com/guide/run/event/service/EventService.java, run/src/main/java/com/guide/run/user/repository/user/UserRepositoryAdminImpl.java
fix : 매칭 userId 에 맞추어 로직 수정 + 정렬 로직 변경중..
=> fix : 매칭 userId 에 맞추어 로직 수정 + 정렬 로직 변경중..

run/src/main/java/com/guide/run/event/service/EventMatchingService.java, run/src/main/java/com/guide/run/partner/entity/matching/repository/UnMatchingRepository.java
=> fix : 매칭 관련 에러 해결

run/src/main/java/com/guide/run/event/controller/EventFormController.java, run/src/main/java/com/guide/run/event/entity/Event.java, run/src/main/java/com/guide/run/event/entity/repository/EventCommentRepositoryImpl.java, run/src/main/java/com/guide/run/event/service/EventFormService.java, run/src/main/java/com/guide/run/event/service/EventMatchingService.java, run/src/main/java/com/guide/run/event/service/EventService.java, run/src/main/java/com/guide/run/partner/entity/matching/repository/MatchingRepository.java, run/src/main/java/com/guide/run/partner/entity/matching/repository/MatchingRepositoryImpl.java
- [O ] Fix
- [ O] Refactor
작업한 내용을 추가합니다.
=> fix : 매칭 테이블 guideId , viId 값 변경에 따른 에러 및 로직 수정

run/src/main/java/com/guide/run/event/entity/repository/EventLikeRepository.java, run/src/main/java/com/guide/run/event/service/EventService.java
=> fix : event 삭제 로직 추가

run/src/main/java/com/guide/run/event/service/EventFormService.java
=> fix : eventForm 삭제 불필요한 코드 삭제

run/src/main/java/com/guide/run/user/service/UserService.java
=> G UI de 206 회원탈퇴 수정

run/src/main/java/com/guide/run/user/service/UserService.java
=> fix : 회원 탈퇴 수정

run/src/main/java/com/guide/run/admin/dto/response/event/CurrentEventResponse.java, run/src/main/java/com/guide/run/event/controller/EventController.java, run/src/main/java/com/guide/run/event/entity/repository/EventFormRepositoryAdminImpl.java, run/src/main/java/com/guide/run/event/entity/repository/EventRepositoryAdminImpl.java, run/src/main/java/com/guide/run/global/scheduler/SchedulerService.java, run/src/main/java/com/guide/run/user/repository/user/UserRepositoryAdminImpl.java
작업한 내용을 추가합니다.
어드민 현재 진행중인 이벤트 에러 수정, 어드민 검색 필터 및 조건 수정, 신청 현황 안 뜨는 에러 수정
어드민 현재 진행중인 이벤트 에러 수정, 어드민 검색 필터 및 조건 수정, 신청 현황 안 뜨는 에러 수정
Resolves: 
See also:
=> fix : 어드민 현재 진행중인 이벤트 에러 수정, 어드민 검색 필터 및 조건 수정, 신청 현황 안 뜨는 에러 수정

run/src/main/java/com/guide/run/global/scheduler/SchedulerService.java
스케줄러 서비스에서 안 쓰는 코드 삭제 후 트랜잭션 어노테이션 추가
=> fix : 스케줄러 수정

run/src/main/java/com/guide/run/event/entity/repository/EventFormRepositoryAdminImpl.java, run/src/main/java/com/guide/run/global/scheduler/SchedulerService.java
스케줄러 에러 수정
스케줄러 에러 수정
Resolves:  
See also:
=> fix : 스케줄러 에러 수정

run/src/main/java/com/guide/run/event/entity/Event.java, run/src/main/java/com/guide/run/event/entity/repository/EventRepository.java, run/src/main/java/com/guide/run/user/service/UserService.java
- [ O] Fix
삭제 시 이벤트 생성자 수정
삭제 시 이벤트 생성자 수정
=> G UI de 213 회원 탈퇴 수정

run/src/main/java/com/guide/run/global/scheduler/SchedulerService.java, run/src/main/java/com/guide/run/global/sms/cool/CoolSMS.java, run/src/main/java/com/guide/run/global/sms/naver/NaverSMS.java, run/src/main/java/com/guide/run/global/sms/naver/dto/MessageDto.java, run/src/main/java/com/guide/run/global/sms/naver/dto/SmsRequest.java, run/src/main/java/com/guide/run/global/sms/naver/dto/SmsResponse.java, run/src/main/java/com/guide/run/user/service/LoginInfoService.java, run/src/main/resources/application-jwt.yml, run/src/main/resources/application-prod.yml, run/src/main/resources/application-qa.yml
sms 서비스 등록, 배포 서버 s3 설정 추가, 레디스 추가
=> feat : sms 서비스 등록, 배포 서버 s3 설정 추가, 레디스 추가

run/src/main/java/com/guide/run/global/sms/cool/CoolSmsService.java, run/src/main/java/com/guide/run/user/service/LoginInfoService.java, run/src/main/resources/application-local.yml, run/src/main/resources/application-prod.yml, run/src/main/resources/application-qa.yml
=> fix : yml 파일 수정, sms 서비스 빈 등록

run/src/main/java/com/guide/run/global/scheduler/SchedulerService.java, run/src/main/java/com/guide/run/global/scheduler/entity/Schedule.java
=> fix : 이벤트 스케줄러 수정

run/src/main/java/com/guide/run/global/scheduler/SchedulerService.java
- [ O] Refactor
작업한 내용을 추가합니다.
=> Refactor : 스케줄러 로그 추가

run/src/main/java/com/guide/run/temp/member/service/MoveService.java
=> feat : 매칭 출석 테이블 미스매치 찾기

run/src/main/java/com/guide/run/global/redis/AuthNumberRepository.java, run/src/main/java/com/guide/run/global/redis/TmpTokenRepository.java, run/src/main/java/com/guide/run/user/service/LoginInfoService.java
=> fix : 토큰 삭제 처리 추가

run/src/main/java/com/guide/run/event/entity/repository/EventRepositoryImpl.java
- [O] Fix
나의 이벤트 정렬 수정
나의 이벤트 정렬 수정
=> fix : 조회 정렬 수정

run/src/main/java/com/guide/run/event/service/EventService.java
=> fix : 이벤트 팝업 수정

run/src/main/java/com/guide/run/event/service/EventFormService.java
=> G UI de 226 guide가 이벤트 신청 취소시 안됨

run/src/main/java/com/guide/run/global/jwt/JwtProvider.java, run/src/main/java/com/guide/run/global/redis/RefreshToken.java, run/src/main/java/com/guide/run/user/controller/SignController.java, run/src/main/java/com/guide/run/user/dto/request/RefreshTokenDto.java, run/src/main/java/com/guide/run/user/dto/response/LoginResponse.java
=> fix : 엑세스 토큰 재발급 방식 수정

run/src/main/java/com/guide/run/event/entity/dto/response/EventPopUpPartner.java
=> fix : 이벤트 팝업 수정(커밋 에러로 재커밋)

run/src/main/java/com/guide/run/event/entity/dto/response/get/DetailEvent.java
=> fix : 이벤트 상세 조회 에러 수정

run/src/main/java/com/guide/run/global/jwt/JwtProvider.java, run/src/main/java/com/guide/run/global/redis/RefreshToken.java
=> fix : refreshToken 임시 보류

run/src/main/java/com/guide/run/user/controller/UserInfoController.java, run/src/main/java/com/guide/run/user/dto/response/UserInfoAll/GuideInfoAllResponse.java, run/src/main/java/com/guide/run/user/dto/response/UserInfoAll/UserInfoAllResponse.java, run/src/main/java/com/guide/run/user/dto/response/UserInfoAll/ViInfoAllResponse.java, run/src/main/java/com/guide/run/user/service/GetUserInfoService.java
작업한 내용을 추가합니다.
- 유저 정보 전체 조회 api를 추가함
- UserInfoAllResponse 패키지 추가
- UserInfoController 추가
- UserInfoService 추가
Resolves: 
See also:
=> feat : 전체 회원 정보 조회 api 생성

run/src/main/java/com/guide/run/event/service/EventMatchingService.java
=> fix : 매칭 취소 에러 수정

run/src/main/java/com/guide/run/event/entity/repository/EventRepositoryImpl.java, run/src/main/java/com/guide/run/global/s3/S3Uploader.java
=> G UI de 235 신청자 명단 그룹별로 나타내기

run/src/main/java/com/guide/run/event/entity/repository/EventRepositoryImpl.java, run/src/main/java/com/guide/run/global/s3/S3Uploader.java
Reverts Link-up-archive-with-VMK/backend#235
=> Revert "G UI de 235 신청자 명단 그룹별로 나타내기"

run/src/main/java/com/guide/run/event/entity/repository/EventRepositoryImpl.java, run/src/main/java/com/guide/run/global/s3/S3Uploader.java, run/src/main/resources/application-local.yml, run/src/main/resources/application-prod.yml, run/src/main/resources/application-qa.yml
=> G UI de 134 나의 이벤트 조회

run/src/main/java/com/guide/run/event/entity/repository/EventFormRepositoryImpl.java, run/src/main/java/com/guide/run/partner/entity/matching/repository/MatchingRepositoryImpl.java, run/src/main/java/com/guide/run/partner/entity/matching/repository/UnMatchingRepositoryImpl.java
=> fix : 신청서 등급이 들어갈 부분에 회원 등급이 들어간 문제 수정

run/src/main/java/com/guide/run/event/entity/repository/EventFormRepositoryImpl.java, run/src/main/java/com/guide/run/partner/entity/matching/repository/MatchingRepositoryImpl.java
=> fix : queryDSL에 필드명 누락

run/src/main/java/com/guide/run/event/entity/repository/EventFormRepositoryImpl.java, run/src/main/java/com/guide/run/partner/entity/matching/repository/MatchingRepositoryImpl.java, run/src/main/java/com/guide/run/partner/entity/matching/repository/UnMatchingRepositoryImpl.java
=> fix : join 절에 이벤트 id 조건 누락 수정

run/src/main/java/com/guide/run/temp/member/repository/AttendanceRepositoryImpl.java
=> 신청서 등급이 들어갈 부분에 회원 러닝 등급으로 되어 있는 오류 수정

run/src/main/java/com/guide/run/temp/member/repository/AttendanceRepositoryImpl.java
Reverts guiderun-project/backend#248
=> Revert "신청서 등급이 들어갈 부분에 회원 러닝 등급으로 되어 있는 오류 수정"

run/src/main/java/com/guide/run/temp/member/repository/AttendanceRepositoryImpl.java
=> fix : 신청서 등급이 들어갈 부분에 회원 러닝 등급으로 되어 있는 오류 수정

run/src/main/java/com/guide/run/temp/member/repository/AttendanceRepositoryImpl.java
=> fix : 신청서 등급이 들어갈 부분에 회원 러닝 등급으로 되어 있는 오류 수정 (join,where절 수정)

run/src/main/java/com/guide/run/temp/member/repository/AttendanceRepositoryImpl.java
Reverts guiderun-project/backend#255
=> Revert "Develop"

run/src/main/java/com/guide/run/temp/member/repository/AttendanceRepositoryImpl.java
Reverts guiderun-project/backend#256
=> Revert "Revert "Develop""

run/src/main/java/com/guide/run/event/entity/dto/response/match/NotMatchUserInfo.java, run/src/main/java/com/guide/run/partner/entity/matching/repository/UnMatchingRepositoryImpl.java
- [ O] Refactor
작업한 내용을 추가합니다.
=> fix : 매칭되지 않은 유저 list response 값에 회원 정보에 기재된 recordDegree값 추가

run/src/main/java/com/guide/run/event/service/EventService.java
작업한 내용을 추가합니다.
이벤트 생성자는 신청서에 기존 러닝 등급이 반영되도록 변경.
신청서에 hopeTeam 필드를 사용자의 러닝 등급으로 추가
=> fix : 이벤트 생성자가 이벤트 신청 시 기존 러닝 등급으로 신청되도록 반영

run/src/main/java/com/guide/run/admin/dto/response/event/AdminEventApplyItem.java, run/src/main/java/com/guide/run/event/entity/dto/response/attend/ParticipationInfo.java, run/src/main/java/com/guide/run/event/entity/dto/response/form/Form.java, run/src/main/java/com/guide/run/event/entity/dto/response/match/MatchedGuideInfo.java, run/src/main/java/com/guide/run/event/entity/dto/response/match/MatchedViInfo.java, run/src/main/java/com/guide/run/event/entity/dto/response/match/NotMatchUserInfo.java, run/src/main/java/com/guide/run/event/entity/repository/EventFormRepositoryAdminImpl.java, run/src/main/java/com/guide/run/event/entity/repository/EventFormRepositoryImpl.java, run/src/main/java/com/guide/run/event/service/EventService.java, run/src/main/java/com/guide/run/partner/entity/matching/repository/MatchingRepositoryImpl.java, run/src/main/java/com/guide/run/partner/entity/matching/repository/UnMatchingRepositoryImpl.java, run/src/main/java/com/guide/run/temp/member/repository/AttendanceRepositoryImpl.java
=> Develop : 신청서/매칭 조회 시 기존 러닝등급 추가, 이벤트 생성자는 자동 신청서에 기존 러닝등급 반영 

run/src/main/java/com/guide/run/event/service/EventFormService.java
=> fix : 간헐적으로 매칭 신청 취소가 안되는 현상 수정

run/src/main/java/com/guide/run/event/entity/Event.java, run/src/main/java/com/guide/run/event/entity/EventForm.java, run/src/main/java/com/guide/run/event/entity/dto/request/EventCreateRequest.java, run/src/main/java/com/guide/run/event/entity/dto/response/EventPopUpResponse.java, run/src/main/java/com/guide/run/event/entity/dto/response/form/GetForm.java, run/src/main/java/com/guide/run/event/entity/dto/response/get/DetailEvent.java, run/src/main/java/com/guide/run/event/service/EventFormService.java, run/src/main/java/com/guide/run/event/service/EventService.java
=> feat : EventCatecory 추가에 따른 코드 수정

run/src/main/java/com/guide/run/event/entity/type/EventCategory.java, run/src/main/java/com/guide/run/event/service/EventService.java
=> G UI de 273 이벤트 type 부여

run/src/main/java/com/guide/run/admin/service/AdminUserService.java, run/src/main/java/com/guide/run/global/sms/cool/CoolSmsService.java, run/src/main/java/com/guide/run/user/service/GuideService.java, run/src/main/java/com/guide/run/user/service/ViService.java, run/src/main/resources/application-prod.yml, run/src/main/resources/application-qa.yml
작업한 내용을 추가합니다.
알림톡 기능 추가. qa 테스트 후 내용 변경 필요
=> feat : 알림톡 기능 추가

run/src/main/java/com/guide/run/global/sms/cool/CoolSmsService.java
=> fix : 메세지 타입 추가

run/src/main/java/com/guide/run/admin/service/AdminUserService.java
=> fix : 템플릿 변수 적용 + 로그 추가

run/src/main/java/com/guide/run/user/service/GuideService.java, run/src/main/java/com/guide/run/user/service/ViService.java
=> fix : 변수 에러 수정

run/src/main/java/com/guide/run/admin/service/AdminUserService.java, run/src/main/java/com/guide/run/global/sms/cool/CoolSMSKakaoController.java, run/src/main/java/com/guide/run/global/sms/cool/CoolSmsController.java, run/src/main/java/com/guide/run/user/service/GuideService.java, run/src/main/java/com/guide/run/user/service/ViService.java
=> fix : 알림톡 코드 전체 수정

run/src/main/java/com/guide/run/user/service/LoginInfoService.java
=> fix : import문 수정 반영

run/src/main/java/com/guide/run/global/sms/cool/CoolSMSKakaoController.java
=> fix : controller 경로 중복 수정

run/src/main/java/com/guide/run/global/sms/cool/CoolSMSKakaoController.java
=> fix : 의존성 주입

run/src/main/java/com/guide/run/admin/service/AdminUserService.java, run/src/main/java/com/guide/run/global/sms/cool/CoolSmsService.java, run/src/main/java/com/guide/run/user/service/GuideService.java, run/src/main/java/com/guide/run/user/service/LoginInfoService.java, run/src/main/java/com/guide/run/user/service/ViService.java
작업한 내용을 추가합니다.
회원 가입 시 관리자에게 알림톡 기능 추가
가입 승인 후 유저에게 알림톡 기능 추가
coolsms 로직에 알림톡 전용 message 생성
전송 함수를 sendOne으로 따로 빼고 sms, 알림톡 2종류로 분류하여 메세지 생성하도록 함.
Resolves: #GUIDE-274
=> feat : 가입 / 가입 승인 알림톡 기능 구현

run/src/main/resources/application-prod.yml, run/src/main/resources/application-qa.yml
작업한 내용을 추가합니다.
알림톡 설정 yml에 적용
Resolves: #GUIDE-274
=> feat : 가입 / 가입 승인 알림톡 설정 반영

run/src/main/java/com/guide/run/admin/service/AdminUserService.java, run/src/main/java/com/guide/run/user/service/GuideService.java, run/src/main/java/com/guide/run/user/service/ViService.java
=> fix : 알림톡 내용 수정

run/src/main/java/com/guide/run/global/security/config/SecurityConfig.java, run/src/main/java/com/guide/run/user/service/GuideService.java, run/src/main/java/com/guide/run/user/service/ViService.java, run/src/main/resources/application-local.yml, run/src/main/resources/application-prod.yml, run/src/main/resources/application-qa.yml
=> fix : 알림톡 내용 수정 + security 권한 설정 수정

run/src/main/java/com/guide/run/global/security/config/SecurityConfig.java
작업한 내용을 추가합니다.
기본 기능은 허용된 사용자만 이용할 수 있도록 수정.
security config 권한을 수정
=> fix : security 권한 설정 수정

run/src/main/java/com/guide/run/global/security/config/SecurityConfig.java
작업한 내용을 추가합니다.
가입만 하고 승인되지 않은 회원은 마이페이지 조회, 프로필 수정만 가능하도록 수정.
미가입 회원은 정보 조회 및 수정 api 접근 불가능하도록 수정.
=> fix : 사용자 권한 설정 수정

run/src/main/java/com/guide/run/user/service/GuideService.java, run/src/main/java/com/guide/run/user/service/ViService.java
작업한 내용을 추가합니다.
- 빌드 에러 해결(변수 중복)
=> fix : 충돌 해결

run/src/main/java/com/guide/run/admin/service/AdminUserService.java, run/src/main/java/com/guide/run/user/controller/SignController.java, run/src/main/java/com/guide/run/user/dto/response/ATAInfo.java, run/src/main/java/com/guide/run/user/service/GuideService.java, run/src/main/java/com/guide/run/user/service/UserService.java, run/src/main/java/com/guide/run/user/service/ViService.java
작업한 내용을 추가합니다.
가입에 오류가 생긴 경우에는 알림톡이 전송되지 않도록 로직을 분리 
알림톡 정보 관련 dto를 추가. 가입 이후 정보 조회 함수를 통해 알림톡 정보를 받고, 해당 정보로 알림톡을 보내도록 로직 수정.
=> fix : 완전히 가입/승인 후 알림톡 전송이 가능하도록 로직 변경

run/src/main/java/com/guide/run/user/controller/SignController.java, run/src/main/java/com/guide/run/user/dto/response/ATAInfo.java, run/src/main/java/com/guide/run/user/service/UserService.java
=> fix : 변수 입력 로직 변경, 로그 추가

run/src/main/java/com/guide/run/global/sms/cool/CoolSmsService.java, run/src/main/java/com/guide/run/user/controller/SignController.java, run/src/main/java/com/guide/run/user/dto/response/ATAInfo.java, run/src/main/java/com/guide/run/user/service/UserService.java
작업한 내용을 추가합니다.
알림톡 로직 변경 
로직 간결하게 정리
다중 메세지로 변경
=> fix : 알림톡 로직 변경

run/src/main/java/com/guide/run/global/cookie/service/CookieService.java, run/src/main/java/com/guide/run/global/jwt/JwtProvider.java, run/src/main/java/com/guide/run/global/redis/RefreshToken.java, run/src/main/java/com/guide/run/user/controller/SignController.java
=> G UI de 276 자동로그인

run/src/main/java/com/guide/run/global/cookie/service/CookieService.java
=> fix : 자동로그인 경로 수정

run/src/main/java/com/guide/run/event/service/EventMatchingService.java
=> fix : 자동 매칭시 privateId가 아닌 userId 사용한 부분 수정

run/src/main/java/com/guide/run/event/service/EventMatchingService.java
=> fix : 자동 매칭시 privateId가 아닌 userId 사용한 부분 추가 수정

run/src/main/java/com/guide/run/event/service/EventMatchingService.java
=> fix : 자동 매칭시 privateId가 아닌 userId 사용한 부분 추추가 수정

run/src/main/java/com/guide/run/event/service/EventMatchingService.java
=> fix : 자동 매칭시 privateId가 아닌 userId 사용한 부분 추추추가 수정

run/src/main/java/com/guide/run/user/controller/LoginInfoController.java, run/src/main/java/com/guide/run/user/controller/SignController.java, run/src/main/resources/application-qa.yml
작업한 내용을 추가합니다.
cors 설정 및 카카오 로그인 경로 변경
=> fix : cors 설정 변경

run/src/main/java/com/guide/run/global/cookie/service/CookieService.java
=> fix : 도메인 변경에 따른 쿠키 설정 변경

run/src/main/java/com/guide/run/event/service/EventMatchingService.java
=> fix : 매칭 시 userID로 조회되는 부분 privateId로 수정

README.md, run/src/main/java/com/guide/run/global/security/config/SecurityConfig.java
=> fix : reissue api 에 new 권한을 가진 사람은 접근할 수 없도록 변경

run/src/main/java/com/guide/run/global/security/config/SecurityConfig.java
Reverts guiderun-project/backend#311
=> Revert "Develop : reissue api를 new 권한인 사용자는 접근할 수 없도록 변경" -> 되돌리기...qa에서 에러 생김..

run/src/main/java/com/guide/run/global/security/config/SecurityConfig.java
Reverts guiderun-project/backend#312
=> Pull request 다시 복구

run/src/main/java/com/guide/run/user/controller/LoginInfoController.java
=> G UI de 288 로그아웃

run/src/main/java/com/guide/run/global/cookie/service/CookieService.java, run/src/main/java/com/guide/run/global/jwt/JwtProvider.java, run/src/main/java/com/guide/run/global/redis/RefreshToken.java, run/src/main/java/com/guide/run/global/security/config/SecurityConfig.java, run/src/main/java/com/guide/run/user/controller/LoginInfoController.java, run/src/main/java/com/guide/run/user/controller/SignController.java
=> fix : 리프레시 토큰 만료 시 쿠키 삭제 처리 + 로그아웃 api에 시큐리티 설정

run/src/main/java/com/guide/run/user/controller/LoginInfoController.java
=> fix : 로그아웃 시 리프레시 토큰 레디스에서 삭제 처리 추가

run/src/main/java/com/guide/run/user/controller/LoginInfoController.java
=> log : 리프레시 토큰 삭제 시 로그 추가

run/src/main/java/com/guide/run/user/controller/LoginInfoController.java
=> fix : else문에서 예외처리 하도록 변경

run/src/main/java/com/guide/run/global/cookie/service/CookieService.java, run/src/main/java/com/guide/run/user/controller/LoginInfoController.java
=> fix : 쿠키 삭제 시 path 와 http 옵션 추가

run/src/main/java/com/guide/run/global/cookie/service/CookieService.java, run/src/main/java/com/guide/run/user/controller/LoginInfoController.java
Reverts guiderun-project/backend#319
=> Revert "fix : 쿠키 삭제 시 path 와 http 옵션 추가"

run/src/main/java/com/guide/run/global/cookie/service/CookieService.java, run/src/main/java/com/guide/run/user/controller/LoginInfoController.java
=> fix : 쿠키 생성 및 삭제 시 path 추가

run/src/main/java/com/guide/run/global/cookie/service/CookieService.java, run/src/main/java/com/guide/run/user/controller/LoginInfoController.java
=> fix : 쿠키 생성 및 삭제 시 path 변경

run/src/main/java/com/guide/run/global/cookie/service/CookieService.java, run/src/main/java/com/guide/run/user/controller/LoginInfoController.java
Reverts guiderun-project/backend#322
=> Revert "fix : 쿠키 생성 및 삭제 시 path 변경"

run/src/main/java/com/guide/run/user/controller/LoginInfoController.java
=> fix : 기존 쿠키 삭제 코드 추가

run/src/main/java/com/guide/run/user/controller/LoginInfoController.java
=> fix : 기존 쿠키 삭제 코드 수정

run/src/main/java/com/guide/run/user/controller/SignController.java
=> fix : null exception 처리

run/src/main/java/com/guide/run/user/controller/SignController.java
=> fix : 자동 로그인 시 쿠키 덮어쓰기

run/src/main/java/com/guide/run/global/cookie/service/CookieService.java, run/src/main/java/com/guide/run/user/controller/SignController.java
=> fix : 로그인/자동 로그인 시 기존 쿠키 만료 및 새 쿠키 생성

run/src/main/java/com/guide/run/global/cookie/service/CookieService.java
=> refactor : 쿠키 유효기간 설정 한 달

run/src/main/java/com/guide/run/admin/controller/AdminEventController.java, run/src/main/java/com/guide/run/admin/dto/response/Guide1365Response.java, run/src/main/java/com/guide/run/admin/service/AdminEventService.java, run/src/main/java/com/guide/run/event/entity/repository/EventRepositoryAdmin.java, run/src/main/java/com/guide/run/event/entity/repository/EventRepositoryAdminImpl.java, run/src/main/java/com/guide/run/user/controller/LoginInfoController.java, run/src/main/java/com/guide/run/user/controller/MypageController.java, run/src/main/java/com/guide/run/user/dto/GlobalUserInfoDto.java, run/src/main/java/com/guide/run/user/dto/GuideSignupDto.java, run/src/main/java/com/guide/run/user/dto/PersonalInfoDto.java, run/src/main/java/com/guide/run/user/dto/ViSignupDto.java, run/src/main/java/com/guide/run/user/dto/response/ProfileResponse.java, run/src/main/java/com/guide/run/user/entity/user/User.java, run/src/main/java/com/guide/run/user/service/GuideService.java, run/src/main/java/com/guide/run/user/service/MypageService.java, run/src/main/java/com/guide/run/user/service/SignupInfoService.java, run/src/main/java/com/guide/run/user/service/ViService.java
작업한 내용을 추가합니다.
- 회원가입 시 1365 id 추가
- 정보 조회 시 1365 id 추가
- 1365 id 따로 추가 api 생성
- 어드민 1365 가이드 조회 api 추가
- User 에 1365 id 추가
=> feat : 1365 id api 추가

run/src/main/java/com/guide/run/admin/dto/response/Guide1365Response.java, run/src/main/java/com/guide/run/user/dto/request/Add1365Dto.java
=> fix : dto 기본 생성자 추가

run/src/main/java/com/guide/run/global/cookie/service/CookieService.java, run/src/main/java/com/guide/run/global/jwt/JwtProvider.java
=> fix : 자동 로그인 시 기존 리프레시 토큰 유효기간을 따르도록 수정

run/src/main/java/com/guide/run/global/cookie/service/CookieService.java, run/src/main/java/com/guide/run/global/jwt/JwtProvider.java
Reverts guiderun-project/backend#336
=> Revert "fix : 자동 로그인 시 기존 리프레시 토큰 유효기간을 따르도록 수정"

run/src/main/java/com/guide/run/user/controller/SignController.java
=> fix : 기존 쿠키 지우고 새 쿠키 반영하는 코드 삭제

run/src/main/java/com/guide/run/global/cookie/service/CookieService.java, run/src/main/java/com/guide/run/user/controller/SignController.java
=> fix : 쿠키 생성 시 로그 추가 및 쿠키 삭제 방식 변경

run/src/main/java/com/guide/run/global/cookie/service/CookieService.java, run/src/main/java/com/guide/run/user/controller/SignController.java
Reverts guiderun-project/backend#339
=> Revert "fix : 쿠키 생성 시 로그 추가 및 쿠키 삭제 방식 변경"

run/src/main/java/com/guide/run/user/controller/SignController.java
Reverts guiderun-project/backend#338
=> Revert "fix : 기존 쿠키 지우고 새 쿠키 반영하는 코드 삭제"

run/src/main/java/com/guide/run/global/cookie/service/CookieService.java, run/src/main/java/com/guide/run/global/jwt/JwtProvider.java
Reverts guiderun-project/backend#337
=> Revert "Revert "fix : 자동 로그인 시 기존 리프레시 토큰 유효기간을 따르도록 수정""

run/src/main/java/com/guide/run/global/cookie/service/CookieService.java, run/src/main/java/com/guide/run/global/jwt/JwtProvider.java
Reverts guiderun-project/backend#342
=> Revert "Revert "Revert "fix : 자동 로그인 시 기존 리프레시 토큰 유효기간을 따르도록 수정"""

run/src/main/java/com/guide/run/event/controller/EventController.java, run/src/main/java/com/guide/run/event/entity/repository/EventRepositoryImpl.java, run/src/main/java/com/guide/run/event/service/EventService.java
=> fix : 참여한 이벤트 내역 where 추가

run/src/main/java/com/guide/run/event/entity/repository/EventRepositoryAdminImpl.java
=> fix : 참여한 이벤트 조회 join 수정

run/src/main/java/com/guide/run/event/controller/EventController.java, run/src/main/java/com/guide/run/event/entity/repository/EventRepositoryAdminImpl.java, run/src/main/java/com/guide/run/event/entity/repository/EventRepositoryImpl.java, run/src/main/java/com/guide/run/event/service/EventService.java
=> fix : 필터링 안되는 에러 수정

run/src/main/java/com/guide/run/temp/member/controller/TMPController.java
=> fix : 전체 이벤트 반영 로직 수정

run/src/main/java/com/guide/run/global/cookie/service/CookieService.java
=> fix : 쿠키 에러 수정중

run/src/main/java/com/guide/run/global/s3/S3Uploader.java
=> fix : s3 업로드시 삭제 추가
